"""Backend services."""

from app.services.analysis_service import (
    AnalysisValidationError,
    parse_and_validate_analysis_response,
    validate_analysis_payload,
)
from app.services.config import ensure_journal_dir, load_config, resolve_journal_dir
from app.services.index import (
    get_index_backup_file_path,
    get_index_file_path,
    list_sessions,
    load_or_rebuild_index,
    rebuild_index,
)
from app.services.json_io import overwrite_json_file, read_json_file, write_json_file
from app.services.processing_queue import SessionProcessingQueue
from app.services.sessions import (
    assemble_session_video,
    create_session,
    delete_session_dir,
    discover_session_dirs,
    extract_session_audio,
    extract_session_thumbnail,
    finalize_session,
    generate_session_id,
    generate_session_slug,
    get_session_audio_path,
    get_session_chunk_manifest_path,
    get_session_chunks_dir,
    get_session_dir,
    get_session_thumbnail_path,
    get_session_video_path,
    load_session_chunk_manifest,
    load_session_bundle,
    load_session_meta,
    load_session_transcript_payload,
    mark_session_read,
    probe_session_video,
    save_session_meta,
    should_skip_processing_pipeline,
    store_session_chunk,
    update_session_meta,
    validate_session_video,
    write_session_chunk_manifest,
)
from app.services.whisper_service import WhisperRuntimeConfig, WhisperService, build_whisper_runtime_config

__all__ = [
    "AnalysisValidationError",
    "parse_and_validate_analysis_response",
    "validate_analysis_payload",
    "create_session",
    "delete_session_dir",
    "discover_session_dirs",
    "ensure_journal_dir",
    "assemble_session_video",
    "finalize_session",
    "generate_session_id",
    "generate_session_slug",
    "extract_session_audio",
    "extract_session_thumbnail",
    "get_session_audio_path",
    "get_session_chunk_manifest_path",
    "get_session_chunks_dir",
    "get_session_dir",
    "get_session_thumbnail_path",
    "get_session_video_path",
    "get_index_backup_file_path",
    "get_index_file_path",
    "list_sessions",
    "load_config",
    "load_session_chunk_manifest",
    "load_session_bundle",
    "load_session_meta",
    "load_session_transcript_payload",
    "mark_session_read",
    "load_or_rebuild_index",
    "overwrite_json_file",
    "probe_session_video",
    "read_json_file",
    "rebuild_index",
    "resolve_journal_dir",
    "save_session_meta",
    "should_skip_processing_pipeline",
    "SessionProcessingQueue",
    "store_session_chunk",
    "update_session_meta",
    "validate_session_video",
    "WhisperRuntimeConfig",
    "WhisperService",
    "build_whisper_runtime_config",
    "write_session_chunk_manifest",
    "write_json_file",
]
